### ISSUE TITLE
Split-target charging is not functioning

### ISSUE THREAD

**Issue by undarl** [sirenfal-factorio/Localized_Charging#2]
**Issue**
When multiple chargeable targets are within range of a charging pole, only one of them at a time is currently being charged. The charging graphics will appear for all targets, but monitoring of the battery charge levels shows only one target being charged.

The culprit seems to be the repeat/until loop at lines 197-218 of control.lua. As written within the contexts of its surrounding loops it appears to dump the entire contents of the interface's energy into the first target.

**Workaround**
Comment out the repeat and until lines (lines 197 and 218). Doing so does enable multiple-target charging. The drawback is that charging is uneven, due to diminishing returns on the energy division by the split value in line 205. It also creates a Zeno's Paradox effect when filling the last bit of batteries because of the efficiency multiplication and the lack of a loop.

**Proposed Solution**
Create another table to be updated at the same time as the split table and which contains `math.floor(interface.energy / split)` for each tower. This value is then used for comparisons in the repeat/until loop in place of the raw interface.energy value so that each target only has their own energy pool to draw upon. 

**Status**
I have a working implementation of the proposed solution, and can set up a PR if desired either separately with other edits mentioned in the [Electric Vehicles](https://github.com/sirenfal-factorio/Localized_Charging/issues/1) question discussion.

**Comment by avosirenfal** [comment]
Should be fixed in f9fdbcb457f0df39f584d3d7c83df9a2c77a3304. My fix is a bit different from yours because I don't want to have bookkeeping for even more data (it's already a mess as it is) and because this math-based fix should mean that unconsumed power from an earlier charge target will be consumed by a later charge target rather than preserved for the next tick (as it would if you split them before charging starts).

The fix works by simply hoisting the split out of the inner loop where the items are charged, and then deriving how much energy is spent per-item and subtracting that from the interface.

I also had some uncommitted fixes apparently related to hardcoded surfaces from an earlier development version. You should merge all of this with your AAI code before submitting a PR.

I'll wait to release this fix on factorio.com until your PR is finished :D

Let me know if you find any more problems. Thank you for the report!

**Comment by undarl** [comment]
That's a clever solution. I gather from the way line 211 is written that any attempt to slap more energy into a battery than it can hold just puts it to max?

**Comment by avosirenfal** [comment]
Yep, sure does. Factorio caps assignments from Lua. You can see that trick in several of my mods

**Comment by undarl** [comment]
Neat.
